{
  "results": [
    {
      "source": {
        "path": "/src/github.sbom.spdx.json",
        "type": "sbom"
      },
      "packages": [
        {
          "package": {
            "name": "jinja2",
            "version": "2.8",
            "ecosystem": "PyPI",
            "commit": ""
          },
          "vulnerabilities": [
            {
              "modified": "2023-11-08T04:00:58Z",
              "published": "2019-04-10T14:30:24Z",
              "schema_version": "1.6.0",
              "id": "GHSA-462w-v97r-4m45",
              "aliases": [
                "CVE-2019-10906",
                "PYSEC-2019-217"
              ],
              "summary": "Jinja2 sandbox escape via string formatting",
              "details": "In Pallets Jinja before 2.10.1, `str.format_map` allows a sandbox escape.\n\nThe sandbox is used to restrict what code can be evaluated when rendering untrusted, user-provided templates. Due to the way string formatting works in Python, the `str.format_map` method could be used to escape the sandbox.\n\nThis issue was previously addressed for the `str.format` method in Jinja 2.8.1, which discusses the issue in detail. However, the less-common `str.format_map` method was overlooked. This release applies the same sandboxing to both methods.\n\nIf you cannot upgrade Jinja, you can override the `is_safe_attribute` method on the sandbox and explicitly disallow the `format_map` method on string objects.",
              "affected": [
                {
                  "package": {
                    "ecosystem": "PyPI",
                    "name": "jinja2",
                    "purl": "pkg:pypi/jinja2"
                  },
                  "ranges": [
                    {
                      "type": "ECOSYSTEM",
                      "events": [
                        {
                          "introduced": "0"
                        },
                        {
                          "fixed": "2.10.1"
                        }
                      ]
                    }
                  ],
                  "versions": [
                    "2.0",
                    "2.0rc1",
                    "2.1",
                    "2.1.1",
                    "2.10",
                    "2.2",
                    "2.2.1",
                    "2.3",
                    "2.3.1",
                    "2.4",
                    "2.4.1",
                    "2.5",
                    "2.5.1",
                    "2.5.2",
                    "2.5.3",
                    "2.5.4",
                    "2.5.5",
                    "2.6",
                    "2.7",
                    "2.7.1",
                    "2.7.2",
                    "2.7.3",
                    "2.8",
                    "2.8.1",
                    "2.9",
                    "2.9.1",
                    "2.9.2",
                    "2.9.3",
                    "2.9.4",
                    "2.9.5",
                    "2.9.6"
                  ],
                  "database_specific": {
                    "source": "https://github.com/github/advisory-database/blob/main/advisories/github-reviewed/2019/04/GHSA-462w-v97r-4m45/GHSA-462w-v97r-4m45.json"
                  }
                }
              ],
              "severity": [
                {
                  "type": "CVSS_V3",
                  "score": "CVSS:3.0/AV:N/AC:L/PR:N/UI:N/S:C/C:H/I:N/A:N"
                }
              ],
              "references": [
                {
                  "type": "ADVISORY",
                  "url": "https://nvd.nist.gov/vuln/detail/CVE-2019-10906"
                },
                {
                  "type": "WEB",
                  "url": "https://access.redhat.com/errata/RHSA-2019:1152"
                },
                {
                  "type": "WEB",
                  "url": "https://access.redhat.com/errata/RHSA-2019:1237"
                },
                {
                  "type": "WEB",
                  "url": "https://access.redhat.com/errata/RHSA-2019:1329"
                },
                {
                  "type": "ADVISORY",
                  "url": "https://github.com/advisories/GHSA-462w-v97r-4m45"
                },
                {
                  "type": "WEB",
                  "url": "https://lists.apache.org/thread.html/09fc842ff444cd43d9d4c510756fec625ef8eb1175f14fd21de2605f@%3Cdevnull.infra.apache.org%3E"
                },
                {
                  "type": "WEB",
                  "url": "https://lists.apache.org/thread.html/2b52b9c8b9d6366a4f1b407a8bde6af28d9fc73fdb3b37695fd0d9ac@%3Cdevnull.infra.apache.org%3E"
                },
                {
                  "type": "WEB",
                  "url": "https://lists.apache.org/thread.html/320441dccbd9a545320f5f07306d711d4bbd31ba43dc9eebcfc602df@%3Cdevnull.infra.apache.org%3E"
                },
                {
                  "type": "WEB",
                  "url": "https://lists.apache.org/thread.html/46c055e173b52d599c648a98199972dbd6a89d2b4c4647b0500f2284@%3Cdevnull.infra.apache.org%3E"
                },
                {
                  "type": "WEB",
                  "url": "https://lists.apache.org/thread.html/57673a78c4d5c870d3f21465c7e2946b9f8285c7c57e54c2ae552f02@%3Ccommits.airflow.apache.org%3E"
                },
                {
                  "type": "WEB",
                  "url": "https://lists.apache.org/thread.html/7f39f01392d320dfb48e4901db68daeece62fd60ef20955966739993@%3Ccommits.airflow.apache.org%3E"
                },
                {
                  "type": "WEB",
                  "url": "https://lists.apache.org/thread.html/b2380d147b508bbcb90d2cad443c159e63e12555966ab4f320ee22da@%3Ccommits.airflow.apache.org%3E"
                },
                {
                  "type": "WEB",
                  "url": "https://lists.apache.org/thread.html/f0c4a03418bcfe70c539c5dbaf99c04c98da13bfa1d3266f08564316@%3Ccommits.airflow.apache.org%3E"
                },
                {
                  "type": "WEB",
                  "url": "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/DSW3QZMFVVR7YE3UT4YRQA272TYAL5AF/"
                },
                {
                  "type": "WEB",
                  "url": "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/QCDYIS254EJMBNWOG4S5QY6AOTOR4TZU/"
                },
                {
                  "type": "WEB",
                  "url": "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/TS7IVZAJBWOHNRDMFJDIZVFCMRP6YIUQ/"
                },
                {
                  "type": "WEB",
                  "url": "https://palletsprojects.com/blog/jinja-2-10-1-released"
                },
                {
                  "type": "WEB",
                  "url": "https://usn.ubuntu.com/4011-1/"
                },
                {
                  "type": "WEB",
                  "url": "https://usn.ubuntu.com/4011-2/"
                },
                {
                  "type": "WEB",
                  "url": "http://lists.opensuse.org/opensuse-security-announce/2019-05/msg00030.html"
                },
                {
                  "type": "WEB",
                  "url": "http://lists.opensuse.org/opensuse-security-announce/2019-06/msg00064.html"
                }
              ],
              "database_specific": {
                "cwe_ids": [
                  "CWE-693"
                ],
                "github_reviewed": true,
                "github_reviewed_at": "2020-06-16T20:57:35Z",
                "nvd_published_at": "2019-04-07T00:29:00Z",
                "severity": "HIGH"
              }
            },
            {
              "modified": "2023-11-08T04:03:28Z",
              "published": "2021-03-19T21:28:05Z",
              "schema_version": "1.6.0",
              "id": "GHSA-g3rq-g295-4j3m",
              "aliases": [
                "CVE-2020-28493",
                "PYSEC-2021-66",
                "SNYK-PYTHON-JINJA2-1012994"
              ],
              "summary": "Regular Expression Denial of Service (ReDoS) in Jinja2",
              "details": "This affects the package jinja2 from 0.0.0 and before 2.11.3. The ReDOS vulnerability of the regex is mainly due to the sub-pattern [a-zA-Z0-9._-]+.[a-zA-Z0-9._-]+ This issue can be mitigated by Markdown to format user content instead of the urlize filter, or by implementing request timeouts and limiting process memory.",
              "affected": [
                {
                  "package": {
                    "ecosystem": "PyPI",
                    "name": "jinja2",
                    "purl": "pkg:pypi/jinja2"
                  },
                  "ranges": [
                    {
                      "type": "ECOSYSTEM",
                      "events": [
                        {
                          "introduced": "0"
                        },
                        {
                          "fixed": "2.11.3"
                        }
                      ]
                    }
                  ],
                  "versions": [
                    "2.0",
                    "2.0rc1",
                    "2.1",
                    "2.1.1",
                    "2.10",
                    "2.10.1",
                    "2.10.2",
                    "2.10.3",
                    "2.11.0",
                    "2.11.1",
                    "2.11.2",
                    "2.2",
                    "2.2.1",
                    "2.3",
                    "2.3.1",
                    "2.4",
                    "2.4.1",
                    "2.5",
                    "2.5.1",
                    "2.5.2",
                    "2.5.3",
                    "2.5.4",
                    "2.5.5",
                    "2.6",
                    "2.7",
                    "2.7.1",
                    "2.7.2",
                    "2.7.3",
                    "2.8",
                    "2.8.1",
                    "2.9",
                    "2.9.1",
                    "2.9.2",
                    "2.9.3",
                    "2.9.4",
                    "2.9.5",
                    "2.9.6"
                  ],
                  "database_specific": {
                    "source": "https://github.com/github/advisory-database/blob/main/advisories/github-reviewed/2021/03/GHSA-g3rq-g295-4j3m/GHSA-g3rq-g295-4j3m.json"
                  },
                  "ecosystem_specific": {
                    "affected_functions": [
                      "jinja2.utils.urlize"
                    ]
                  }
                }
              ],
              "severity": [
                {
                  "type": "CVSS_V3",
                  "score": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:L"
                }
              ],
              "references": [
                {
                  "type": "ADVISORY",
                  "url": "https://nvd.nist.gov/vuln/detail/CVE-2020-28493"
                },
                {
                  "type": "WEB",
                  "url": "https://github.com/pallets/jinja/pull/1343"
                },
                {
                  "type": "WEB",
                  "url": "https://github.com/pallets/jinja/commit/15ef8f09b659f9100610583938005a7a10472d4d"
                },
                {
                  "type": "PACKAGE",
                  "url": "https://github.com/pallets/jinja"
                },
                {
                  "type": "WEB",
                  "url": "https://github.com/pallets/jinja/blob/ab81fd9c277900c85da0c322a2ff9d68a235b2e6/src/jinja2/utils.py%23L20"
                },
                {
                  "type": "WEB",
                  "url": "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/PVAKCOO7VBVUBM3Q6CBBTPBFNP5NDXF4/"
                },
                {
                  "type": "WEB",
                  "url": "https://security.gentoo.org/glsa/202107-19"
                },
                {
                  "type": "WEB",
                  "url": "https://snyk.io/vuln/SNYK-PYTHON-JINJA2-1012994"
                }
              ],
              "database_specific": {
                "cwe_ids": [
                  "CWE-400"
                ],
                "github_reviewed": true,
                "github_reviewed_at": "2021-03-13T01:08:09Z",
                "nvd_published_at": "2021-02-01T20:15:00Z",
                "severity": "MODERATE"
              }
            },
            {
              "modified": "2023-11-08T03:58:21Z",
              "published": "2019-04-10T14:30:13Z",
              "schema_version": "1.6.0",
              "id": "GHSA-hj2j-77xm-mc5v",
              "aliases": [
                "CVE-2016-10745",
                "PYSEC-2019-220"
              ],
              "summary": "High severity vulnerability that affects Jinja2",
              "details": "In Pallets Jinja before 2.8.1, str.format allows a sandbox escape.",
              "affected": [
                {
                  "package": {
                    "ecosystem": "PyPI",
                    "name": "jinja2",
                    "purl": "pkg:pypi/jinja2"
                  },
                  "ranges": [
                    {
                      "type": "ECOSYSTEM",
                      "events": [
                        {
                          "introduced": "0"
                        },
                        {
                          "fixed": "2.8.1"
                        }
                      ]
                    }
                  ],
                  "versions": [
                    "2.0",
                    "2.0rc1",
                    "2.1",
                    "2.1.1",
                    "2.2",
                    "2.2.1",
                    "2.3",
                    "2.3.1",
                    "2.4",
                    "2.4.1",
                    "2.5",
                    "2.5.1",
                    "2.5.2",
                    "2.5.3",
                    "2.5.4",
                    "2.5.5",
                    "2.6",
                    "2.7",
                    "2.7.1",
                    "2.7.2",
                    "2.7.3",
                    "2.8"
                  ],
                  "database_specific": {
                    "source": "https://github.com/github/advisory-database/blob/main/advisories/github-reviewed/2019/04/GHSA-hj2j-77xm-mc5v/GHSA-hj2j-77xm-mc5v.json"
                  }
                }
              ],
              "severity": [
                {
                  "type": "CVSS_V3",
                  "score": "CVSS:3.0/AV:N/AC:L/PR:N/UI:N/S:C/C:H/I:N/A:N"
                }
              ],
              "references": [
                {
                  "type": "ADVISORY",
                  "url": "https://nvd.nist.gov/vuln/detail/CVE-2016-10745"
                },
                {
                  "type": "WEB",
                  "url": "https://github.com/pallets/jinja/commit/9b53045c34e61013dc8f09b7e52a555fa16bed16"
                },
                {
                  "type": "WEB",
                  "url": "https://access.redhat.com/errata/RHSA-2019:1022"
                },
                {
                  "type": "WEB",
                  "url": "https://access.redhat.com/errata/RHSA-2019:1237"
                },
                {
                  "type": "WEB",
                  "url": "https://access.redhat.com/errata/RHSA-2019:1260"
                },
                {
                  "type": "WEB",
                  "url": "https://access.redhat.com/errata/RHSA-2019:3964"
                },
                {
                  "type": "WEB",
                  "url": "https://access.redhat.com/errata/RHSA-2019:4062"
                },
                {
                  "type": "ADVISORY",
                  "url": "https://github.com/advisories/GHSA-hj2j-77xm-mc5v"
                },
                {
                  "type": "PACKAGE",
                  "url": "https://github.com/pallets/jinja"
                },
                {
                  "type": "WEB",
                  "url": "https://palletsprojects.com/blog/jinja-281-released/"
                },
                {
                  "type": "WEB",
                  "url": "https://usn.ubuntu.com/4011-1/"
                },
                {
                  "type": "WEB",
                  "url": "https://usn.ubuntu.com/4011-2/"
                },
                {
                  "type": "WEB",
                  "url": "http://lists.opensuse.org/opensuse-security-announce/2019-05/msg00030.html"
                },
                {
                  "type": "WEB",
                  "url": "http://lists.opensuse.org/opensuse-security-announce/2019-06/msg00064.html"
                }
              ],
              "database_specific": {
                "cwe_ids": [
                  "CWE-134"
                ],
                "github_reviewed": true,
                "github_reviewed_at": "2020-06-16T21:40:24Z",
                "nvd_published_at": null,
                "severity": "HIGH"
              }
            },
            {
              "modified": "2023-11-08T04:00:58Z",
              "published": "2019-04-07T00:29:00Z",
              "schema_version": "1.6.0",
              "id": "PYSEC-2019-217",
              "aliases": [
                "CVE-2019-10906",
                "GHSA-462w-v97r-4m45"
              ],
              "details": "In Pallets Jinja before 2.10.1, str.format_map allows a sandbox escape.",
              "affected": [
                {
                  "package": {
                    "ecosystem": "PyPI",
                    "name": "jinja2",
                    "purl": "pkg:pypi/jinja2"
                  },
                  "ranges": [
                    {
                      "type": "ECOSYSTEM",
                      "events": [
                        {
                          "introduced": "0"
                        },
                        {
                          "fixed": "2.10.1"
                        }
                      ]
                    }
                  ],
                  "versions": [
                    "2.0",
                    "2.0rc1",
                    "2.1",
                    "2.1.1",
                    "2.10",
                    "2.2",
                    "2.2.1",
                    "2.3",
                    "2.3.1",
                    "2.4",
                    "2.4.1",
                    "2.5",
                    "2.5.1",
                    "2.5.2",
                    "2.5.3",
                    "2.5.4",
                    "2.5.5",
                    "2.6",
                    "2.7",
                    "2.7.1",
                    "2.7.2",
                    "2.7.3",
                    "2.8",
                    "2.8.1",
                    "2.9",
                    "2.9.1",
                    "2.9.2",
                    "2.9.3",
                    "2.9.4",
                    "2.9.5",
                    "2.9.6"
                  ],
                  "database_specific": {
                    "source": "https://github.com/pypa/advisory-database/blob/main/vulns/jinja2/PYSEC-2019-217.yaml"
                  }
                }
              ],
              "references": [
                {
                  "type": "ARTICLE",
                  "url": "https://palletsprojects.com/blog/jinja-2-10-1-released"
                },
                {
                  "type": "WEB",
                  "url": "https://lists.apache.org/thread.html/b2380d147b508bbcb90d2cad443c159e63e12555966ab4f320ee22da@%3Ccommits.airflow.apache.org%3E"
                },
                {
                  "type": "WEB",
                  "url": "https://lists.apache.org/thread.html/46c055e173b52d599c648a98199972dbd6a89d2b4c4647b0500f2284@%3Cdevnull.infra.apache.org%3E"
                },
                {
                  "type": "WEB",
                  "url": "https://lists.apache.org/thread.html/f0c4a03418bcfe70c539c5dbaf99c04c98da13bfa1d3266f08564316@%3Ccommits.airflow.apache.org%3E"
                },
                {
                  "type": "WEB",
                  "url": "https://lists.apache.org/thread.html/7f39f01392d320dfb48e4901db68daeece62fd60ef20955966739993@%3Ccommits.airflow.apache.org%3E"
                },
                {
                  "type": "WEB",
                  "url": "https://lists.apache.org/thread.html/57673a78c4d5c870d3f21465c7e2946b9f8285c7c57e54c2ae552f02@%3Ccommits.airflow.apache.org%3E"
                },
                {
                  "type": "WEB",
                  "url": "https://lists.apache.org/thread.html/320441dccbd9a545320f5f07306d711d4bbd31ba43dc9eebcfc602df@%3Cdevnull.infra.apache.org%3E"
                },
                {
                  "type": "WEB",
                  "url": "https://lists.apache.org/thread.html/2b52b9c8b9d6366a4f1b407a8bde6af28d9fc73fdb3b37695fd0d9ac@%3Cdevnull.infra.apache.org%3E"
                },
                {
                  "type": "WEB",
                  "url": "https://lists.apache.org/thread.html/09fc842ff444cd43d9d4c510756fec625ef8eb1175f14fd21de2605f@%3Cdevnull.infra.apache.org%3E"
                },
                {
                  "type": "WEB",
                  "url": "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/QCDYIS254EJMBNWOG4S5QY6AOTOR4TZU/"
                },
                {
                  "type": "WEB",
                  "url": "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/DSW3QZMFVVR7YE3UT4YRQA272TYAL5AF/"
                },
                {
                  "type": "WEB",
                  "url": "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/TS7IVZAJBWOHNRDMFJDIZVFCMRP6YIUQ/"
                },
                {
                  "type": "ADVISORY",
                  "url": "https://access.redhat.com/errata/RHSA-2019:1152"
                },
                {
                  "type": "WEB",
                  "url": "http://lists.opensuse.org/opensuse-security-announce/2019-05/msg00030.html"
                },
                {
                  "type": "ADVISORY",
                  "url": "https://access.redhat.com/errata/RHSA-2019:1237"
                },
                {
                  "type": "ADVISORY",
                  "url": "https://access.redhat.com/errata/RHSA-2019:1329"
                },
                {
                  "type": "WEB",
                  "url": "https://usn.ubuntu.com/4011-1/"
                },
                {
                  "type": "WEB",
                  "url": "https://usn.ubuntu.com/4011-2/"
                },
                {
                  "type": "WEB",
                  "url": "http://lists.opensuse.org/opensuse-security-announce/2019-06/msg00064.html"
                },
                {
                  "type": "ADVISORY",
                  "url": "https://github.com/advisories/GHSA-462w-v97r-4m45"
                }
              ]
            },
            {
              "modified": "2023-11-08T03:58:21Z",
              "published": "2019-04-08T13:29:00Z",
              "schema_version": "1.6.0",
              "id": "PYSEC-2019-220",
              "aliases": [
                "CVE-2016-10745",
                "GHSA-hj2j-77xm-mc5v"
              ],
              "details": "In Pallets Jinja before 2.8.1, str.format allows a sandbox escape.",
              "affected": [
                {
                  "package": {
                    "ecosystem": "PyPI",
                    "name": "jinja2",
                    "purl": "pkg:pypi/jinja2"
                  },
                  "ranges": [
                    {
                      "type": "GIT",
                      "events": [
                        {
                          "introduced": "0"
                        },
                        {
                          "fixed": "9b53045c34e61013dc8f09b7e52a555fa16bed16"
                        }
                      ],
                      "repo": "https://github.com/pallets/jinja"
                    },
                    {
                      "type": "ECOSYSTEM",
                      "events": [
                        {
                          "introduced": "0"
                        },
                        {
                          "fixed": "2.8.1"
                        }
                      ]
                    }
                  ],
                  "versions": [
                    "2.0",
                    "2.0rc1",
                    "2.1",
                    "2.1.1",
                    "2.2",
                    "2.2.1",
                    "2.3",
                    "2.3.1",
                    "2.4",
                    "2.4.1",
                    "2.5",
                    "2.5.1",
                    "2.5.2",
                    "2.5.3",
                    "2.5.4",
                    "2.5.5",
                    "2.6",
                    "2.7",
                    "2.7.1",
                    "2.7.2",
                    "2.7.3",
                    "2.8"
                  ],
                  "database_specific": {
                    "source": "https://github.com/pypa/advisory-database/blob/main/vulns/jinja2/PYSEC-2019-220.yaml"
                  }
                }
              ],
              "references": [
                {
                  "type": "ARTICLE",
                  "url": "https://palletsprojects.com/blog/jinja-281-released/"
                },
                {
                  "type": "FIX",
                  "url": "https://github.com/pallets/jinja/commit/9b53045c34e61013dc8f09b7e52a555fa16bed16"
                },
                {
                  "type": "ADVISORY",
                  "url": "https://access.redhat.com/errata/RHSA-2019:1022"
                },
                {
                  "type": "WEB",
                  "url": "http://lists.opensuse.org/opensuse-security-announce/2019-05/msg00030.html"
                },
                {
                  "type": "ADVISORY",
                  "url": "https://access.redhat.com/errata/RHSA-2019:1237"
                },
                {
                  "type": "ADVISORY",
                  "url": "https://access.redhat.com/errata/RHSA-2019:1260"
                },
                {
                  "type": "WEB",
                  "url": "https://usn.ubuntu.com/4011-1/"
                },
                {
                  "type": "WEB",
                  "url": "https://usn.ubuntu.com/4011-2/"
                },
                {
                  "type": "WEB",
                  "url": "http://lists.opensuse.org/opensuse-security-announce/2019-06/msg00064.html"
                },
                {
                  "type": "ADVISORY",
                  "url": "https://access.redhat.com/errata/RHSA-2019:3964"
                },
                {
                  "type": "ADVISORY",
                  "url": "https://access.redhat.com/errata/RHSA-2019:4062"
                },
                {
                  "type": "ADVISORY",
                  "url": "https://github.com/advisories/GHSA-hj2j-77xm-mc5v"
                }
              ]
            },
            {
              "modified": "2023-11-08T04:03:28Z",
              "published": "2021-02-01T20:15:00Z",
              "schema_version": "1.6.0",
              "id": "PYSEC-2021-66",
              "aliases": [
                "CVE-2020-28493",
                "GHSA-g3rq-g295-4j3m",
                "SNYK-PYTHON-JINJA2-1012994"
              ],
              "details": "This affects the package jinja2 from 0.0.0 and before 2.11.3. The ReDoS vulnerability is mainly due to the `_punctuation_re regex` operator and its use of multiple wildcards. The last wildcard is the most exploitable as it searches for trailing punctuation. This issue can be mitigated by Markdown to format user content instead of the urlize filter, or by implementing request timeouts and limiting process memory.",
              "affected": [
                {
                  "package": {
                    "ecosystem": "PyPI",
                    "name": "jinja2",
                    "purl": "pkg:pypi/jinja2"
                  },
                  "ranges": [
                    {
                      "type": "ECOSYSTEM",
                      "events": [
                        {
                          "introduced": "0"
                        },
                        {
                          "fixed": "2.11.3"
                        }
                      ]
                    }
                  ],
                  "versions": [
                    "2.0rc1",
                    "2.0",
                    "2.1",
                    "2.1.1",
                    "2.2",
                    "2.2.1",
                    "2.3",
                    "2.3.1",
                    "2.4",
                    "2.4.1",
                    "2.5",
                    "2.5.1",
                    "2.5.2",
                    "2.5.3",
                    "2.5.4",
                    "2.5.5",
                    "2.6",
                    "2.7",
                    "2.7.1",
                    "2.7.2",
                    "2.7.3",
                    "2.8",
                    "2.8.1",
                    "2.9",
                    "2.9.1",
                    "2.9.2",
                    "2.9.3",
                    "2.9.4",
                    "2.9.5",
                    "2.9.6",
                    "2.10",
                    "2.10.1",
                    "2.10.2",
                    "2.10.3",
                    "2.11.0",
                    "2.11.1",
                    "2.11.2"
                  ],
                  "database_specific": {
                    "source": "https://github.com/pypa/advisory-database/blob/main/vulns/jinja2/PYSEC-2021-66.yaml"
                  }
                }
              ],
              "references": [
                {
                  "type": "WEB",
                  "url": "https://github.com/pallets/jinja/blob/ab81fd9c277900c85da0c322a2ff9d68a235b2e6/src/jinja2/utils.py%23L20"
                },
                {
                  "type": "WEB",
                  "url": "https://github.com/pallets/jinja/pull/1343"
                },
                {
                  "type": "ADVISORY",
                  "url": "https://snyk.io/vuln/SNYK-PYTHON-JINJA2-1012994"
                },
                {
                  "type": "WEB",
                  "url": "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/PVAKCOO7VBVUBM3Q6CBBTPBFNP5NDXF4/"
                },
                {
                  "type": "ADVISORY",
                  "url": "https://github.com/advisories/GHSA-g3rq-g295-4j3m"
                }
              ]
            }
          ],
          "groups": [
            {
              "ids": [
                "GHSA-462w-v97r-4m45",
                "PYSEC-2019-217"
              ]
            },
            {
              "ids": [
                "GHSA-g3rq-g295-4j3m",
                "PYSEC-2021-66"
              ]
            },
            {
              "ids": [
                "GHSA-hj2j-77xm-mc5v",
                "PYSEC-2019-220"
              ]
            }
          ]
        },
        {
          "package": {
            "name": "pygments",
            "version": "2.1.3",
            "ecosystem": "PyPI",
            "commit": ""
          },
          "vulnerabilities": [
            {
              "modified": "2023-11-08T04:04:36Z",
              "published": "2021-04-20T16:35:47Z",
              "schema_version": "1.6.0",
              "id": "GHSA-9w8r-397f-prfh",
              "aliases": [
                "CVE-2021-20270",
                "PYSEC-2021-140"
              ],
              "summary": "Infinite Loop in Pygments",
              "details": "An infinite loop in SMLLexer in Pygments versions 1.5 to 2.7.3 may lead to denial of service when performing syntax highlighting of a Standard ML (SML) source file, as demonstrated by input that only contains the \"exception\" keyword.",
              "affected": [
                {
                  "package": {
                    "ecosystem": "PyPI",
                    "name": "pygments",
                    "purl": "pkg:pypi/pygments"
                  },
                  "ranges": [
                    {
                      "type": "ECOSYSTEM",
                      "events": [
                        {
                          "introduced": "1.5"
                        },
                        {
                          "fixed": "2.7.4"
                        }
                      ]
                    }
                  ],
                  "versions": [
                    "1.5",
                    "1.6",
                    "1.6rc1",
                    "2.0",
                    "2.0.1",
                    "2.0.2",
                    "2.0rc1",
                    "2.1",
                    "2.1.1",
                    "2.1.2",
                    "2.1.3",
                    "2.2.0",
                    "2.3.0",
                    "2.3.1",
                    "2.4.0",
                    "2.4.1",
                    "2.4.2",
                    "2.5.1",
                    "2.5.2",
                    "2.6.0",
                    "2.6.1",
                    "2.7.0",
                    "2.7.1",
                    "2.7.2",
                    "2.7.3"
                  ],
                  "database_specific": {
                    "source": "https://github.com/github/advisory-database/blob/main/advisories/github-reviewed/2021/04/GHSA-9w8r-397f-prfh/GHSA-9w8r-397f-prfh.json"
                  }
                }
              ],
              "severity": [
                {
                  "type": "CVSS_V3",
                  "score": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H"
                }
              ],
              "references": [
                {
                  "type": "ADVISORY",
                  "url": "https://nvd.nist.gov/vuln/detail/CVE-2021-20270"
                },
                {
                  "type": "WEB",
                  "url": "https://github.com/pygments/pygments/commit/f91804ff4772e3ab41f46e28d370f57898700333"
                },
                {
                  "type": "WEB",
                  "url": "https://bugzilla.redhat.com/show_bug.cgi?id=1922136"
                },
                {
                  "type": "PACKAGE",
                  "url": "https://github.com/pygments/pygments"
                },
                {
                  "type": "WEB",
                  "url": "https://lists.debian.org/debian-lts-announce/2021/05/msg00003.html"
                },
                {
                  "type": "WEB",
                  "url": "https://lists.debian.org/debian-lts-announce/2021/05/msg00006.html"
                },
                {
                  "type": "WEB",
                  "url": "https://www.debian.org/security/2021/dsa-4889"
                },
                {
                  "type": "WEB",
                  "url": "https://www.oracle.com/security-alerts/cpuoct2021.html"
                }
              ],
              "database_specific": {
                "cwe_ids": [
                  "CWE-835"
                ],
                "github_reviewed": true,
                "github_reviewed_at": "2021-04-12T20:58:03Z",
                "nvd_published_at": "2021-03-23T17:15:00Z",
                "severity": "HIGH"
              }
            },
            {
              "modified": "2023-11-08T04:10:25Z",
              "published": "2023-07-19T15:30:26Z",
              "schema_version": "1.6.0",
              "id": "GHSA-mrwq-x4v8-fh7p",
              "aliases": [
                "CVE-2022-40896",
                "PYSEC-2023-117"
              ],
              "summary": "Pygments vulnerable to ReDoS",
              "details": "A ReDoS issue was discovered in `pygments/lexers/smithy.py` in Pygments until 2.15.0 via SmithyLexer.",
              "affected": [
                {
                  "package": {
                    "ecosystem": "PyPI",
                    "name": "pygments",
                    "purl": "pkg:pypi/pygments"
                  },
                  "ranges": [
                    {
                      "type": "ECOSYSTEM",
                      "events": [
                        {
                          "introduced": "0"
                        },
                        {
                          "fixed": "2.15.0"
                        }
                      ]
                    }
                  ],
                  "versions": [
                    "0.10",
                    "0.11",
                    "0.11.1",
                    "0.5",
                    "0.5.1",
                    "0.6",
                    "0.7",
                    "0.7.1",
                    "0.8",
                    "0.8.1",
                    "0.9",
                    "1.0",
                    "1.1",
                    "1.1.1",
                    "1.2",
                    "1.2.1",
                    "1.2.2",
                    "1.3",
                    "1.3.1",
                    "1.4",
                    "1.5",
                    "1.6",
                    "1.6rc1",
                    "2.0",
                    "2.0.1",
                    "2.0.2",
                    "2.0rc1",
                    "2.1",
                    "2.1.1",
                    "2.1.2",
                    "2.1.3",
                    "2.10.0",
                    "2.11.0",
                    "2.11.1",
                    "2.11.2",
                    "2.12.0",
                    "2.13.0",
                    "2.14.0",
                    "2.2.0",
                    "2.3.0",
                    "2.3.1",
                    "2.4.0",
                    "2.4.1",
                    "2.4.2",
                    "2.5.1",
                    "2.5.2",
                    "2.6.0",
                    "2.6.1",
                    "2.7.0",
                    "2.7.1",
                    "2.7.2",
                    "2.7.3",
                    "2.7.4",
                    "2.8.0",
                    "2.8.1",
                    "2.9.0"
                  ],
                  "database_specific": {
                    "source": "https://github.com/github/advisory-database/blob/main/advisories/github-reviewed/2023/07/GHSA-mrwq-x4v8-fh7p/GHSA-mrwq-x4v8-fh7p.json"
                  },
                  "ecosystem_specific": {
                    "affected_functions": [
                      "pygments.lexers.templates.SqlJinjaLexer.analyse_text",
                      "pygments.lexers.smithy.SmithyLexer",
                      "pygments.lexers.configs.PropertiesLexer"
                    ]
                  }
                }
              ],
              "severity": [
                {
                  "type": "CVSS_V3",
                  "score": "CVSS:3.1/AV:L/AC:L/PR:N/UI:R/S:U/C:N/I:N/A:H"
                }
              ],
              "references": [
                {
                  "type": "ADVISORY",
                  "url": "https://nvd.nist.gov/vuln/detail/CVE-2022-40896"
                },
                {
                  "type": "WEB",
                  "url": "https://github.com/pygments/pygments/commit/97eb3d5ec7c1b3ea4fcf9dee30a2309cf92bd194"
                },
                {
                  "type": "WEB",
                  "url": "https://github.com/pygments/pygments/commit/dd52102c38ebe78cd57748e09f38929fd283ad04"
                },
                {
                  "type": "WEB",
                  "url": "https://github.com/pygments/pygments/commit/fdf182a7af85b1deeeb637ca970d31935e7c9d52"
                },
                {
                  "type": "PACKAGE",
                  "url": "https://github.com/pygments/pygments"
                },
                {
                  "type": "WEB",
                  "url": "https://github.com/pygments/pygments/blob/master/pygments/lexers/smithy.py#L61"
                },
                {
                  "type": "WEB",
                  "url": "https://github.com/pypa/advisory-database/tree/main/vulns/pygments/PYSEC-2023-117.yaml"
                },
                {
                  "type": "WEB",
                  "url": "https://pypi.org/project/Pygments/"
                },
                {
                  "type": "WEB",
                  "url": "https://pyup.io/posts/pyup-discovers-redos-vulnerabilities-in-top-python-packages-part-2/"
                }
              ],
              "database_specific": {
                "cwe_ids": [
                  "CWE-434"
                ],
                "github_reviewed": true,
                "github_reviewed_at": "2023-07-20T11:00:04Z",
                "nvd_published_at": "2023-07-19T15:15:10Z",
                "severity": "MODERATE"
              }
            },
            {
              "modified": "2023-11-08T04:05:24Z",
              "published": "2021-03-29T16:33:03Z",
              "schema_version": "1.6.0",
              "id": "GHSA-pq64-v7f5-gqh8",
              "aliases": [
                "CVE-2021-27291",
                "PYSEC-2021-141"
              ],
              "summary": "Pygments vulnerable to Regular Expression Denial of Service (ReDoS)",
              "details": "In pygments 1.1+, fixed in 2.7.4, the lexers used to parse programming languages rely heavily on regular expressions. Some of the regular expressions have exponential or cubic worst-case complexity and are vulnerable to ReDoS. By crafting malicious input, an attacker can cause a denial of service.",
              "affected": [
                {
                  "package": {
                    "ecosystem": "PyPI",
                    "name": "pygments",
                    "purl": "pkg:pypi/pygments"
                  },
                  "ranges": [
                    {
                      "type": "ECOSYSTEM",
                      "events": [
                        {
                          "introduced": "1.1"
                        },
                        {
                          "fixed": "2.7.4"
                        }
                      ]
                    }
                  ],
                  "versions": [
                    "1.1",
                    "1.1.1",
                    "1.2",
                    "1.2.1",
                    "1.2.2",
                    "1.3",
                    "1.3.1",
                    "1.4",
                    "1.5",
                    "1.6",
                    "1.6rc1",
                    "2.0",
                    "2.0.1",
                    "2.0.2",
                    "2.0rc1",
                    "2.1",
                    "2.1.1",
                    "2.1.2",
                    "2.1.3",
                    "2.2.0",
                    "2.3.0",
                    "2.3.1",
                    "2.4.0",
                    "2.4.1",
                    "2.4.2",
                    "2.5.1",
                    "2.5.2",
                    "2.6.0",
                    "2.6.1",
                    "2.7.0",
                    "2.7.1",
                    "2.7.2",
                    "2.7.3"
                  ],
                  "database_specific": {
                    "source": "https://github.com/github/advisory-database/blob/main/advisories/github-reviewed/2021/03/GHSA-pq64-v7f5-gqh8/GHSA-pq64-v7f5-gqh8.json"
                  }
                }
              ],
              "severity": [
                {
                  "type": "CVSS_V3",
                  "score": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H"
                }
              ],
              "references": [
                {
                  "type": "ADVISORY",
                  "url": "https://nvd.nist.gov/vuln/detail/CVE-2021-27291"
                },
                {
                  "type": "WEB",
                  "url": "https://github.com/pygments/pygments/commit/2e7e8c4a7b318f4032493773732754e418279a14"
                },
                {
                  "type": "WEB",
                  "url": "https://gist.github.com/b-c-ds/b1a2cc0c68a35c57188575eb496de5ce"
                },
                {
                  "type": "PACKAGE",
                  "url": "https://github.com/pygments/pygments"
                },
                {
                  "type": "WEB",
                  "url": "https://lists.debian.org/debian-lts-announce/2021/03/msg00024.html"
                },
                {
                  "type": "WEB",
                  "url": "https://lists.debian.org/debian-lts-announce/2021/05/msg00003.html"
                },
                {
                  "type": "WEB",
                  "url": "https://lists.debian.org/debian-lts-announce/2021/05/msg00006.html"
                },
                {
                  "type": "WEB",
                  "url": "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/GSJRFHALQ7E3UV4FFMFU2YQ6LUDHAI55/"
                },
                {
                  "type": "WEB",
                  "url": "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/WSLD67LFGXOX2K5YNESSWAS4AGZIJTUQ/"
                },
                {
                  "type": "WEB",
                  "url": "https://www.debian.org/security/2021/dsa-4878"
                },
                {
                  "type": "WEB",
                  "url": "https://www.debian.org/security/2021/dsa-4889"
                }
              ],
              "database_specific": {
                "cwe_ids": [
                  "CWE-400"
                ],
                "github_reviewed": true,
                "github_reviewed_at": "2021-03-22T20:28:40Z",
                "nvd_published_at": "2021-03-17T13:15:00Z",
                "severity": "HIGH"
              }
            },
            {
              "modified": "2023-11-08T04:04:36Z",
              "published": "2021-03-23T17:15:00Z",
              "schema_version": "1.6.0",
              "id": "PYSEC-2021-140",
              "aliases": [
                "CVE-2021-20270",
                "GHSA-9w8r-397f-prfh"
              ],
              "details": "An infinite loop in SMLLexer in Pygments versions 1.5 to 2.7.3 may lead to denial of service when performing syntax highlighting of a Standard ML (SML) source file, as demonstrated by input that only contains the \"exception\" keyword.",
              "affected": [
                {
                  "package": {
                    "ecosystem": "PyPI",
                    "name": "pygments",
                    "purl": "pkg:pypi/pygments"
                  },
                  "ranges": [
                    {
                      "type": "ECOSYSTEM",
                      "events": [
                        {
                          "introduced": "1.5"
                        },
                        {
                          "fixed": "2.7.4"
                        }
                      ]
                    }
                  ],
                  "versions": [
                    "1.5",
                    "1.6",
                    "1.6rc1",
                    "2.0",
                    "2.0.1",
                    "2.0.2",
                    "2.0rc1",
                    "2.1",
                    "2.1.1",
                    "2.1.2",
                    "2.1.3",
                    "2.2.0",
                    "2.3.0",
                    "2.3.1",
                    "2.4.0",
                    "2.4.1",
                    "2.4.2",
                    "2.5.1",
                    "2.5.2",
                    "2.6.0",
                    "2.6.1",
                    "2.7.0",
                    "2.7.1",
                    "2.7.2",
                    "2.7.3"
                  ],
                  "database_specific": {
                    "source": "https://github.com/pypa/advisory-database/blob/main/vulns/pygments/PYSEC-2021-140.yaml"
                  }
                }
              ],
              "references": [
                {
                  "type": "REPORT",
                  "url": "https://bugzilla.redhat.com/show_bug.cgi?id=1922136"
                },
                {
                  "type": "ADVISORY",
                  "url": "https://www.debian.org/security/2021/dsa-4889"
                },
                {
                  "type": "WEB",
                  "url": "https://lists.debian.org/debian-lts-announce/2021/05/msg00003.html"
                },
                {
                  "type": "WEB",
                  "url": "https://lists.debian.org/debian-lts-announce/2021/05/msg00006.html"
                },
                {
                  "type": "ADVISORY",
                  "url": "https://github.com/advisories/GHSA-9w8r-397f-prfh"
                }
              ]
            },
            {
              "modified": "2023-11-08T04:05:24Z",
              "published": "2021-03-17T13:15:00Z",
              "schema_version": "1.6.0",
              "id": "PYSEC-2021-141",
              "aliases": [
                "CVE-2021-27291",
                "GHSA-pq64-v7f5-gqh8"
              ],
              "details": "In pygments 1.1+, fixed in 2.7.4, the lexers used to parse programming languages rely heavily on regular expressions. Some of the regular expressions have exponential or cubic worst-case complexity and are vulnerable to ReDoS. By crafting malicious input, an attacker can cause a denial of service.",
              "affected": [
                {
                  "package": {
                    "ecosystem": "PyPI",
                    "name": "pygments",
                    "purl": "pkg:pypi/pygments"
                  },
                  "ranges": [
                    {
                      "type": "GIT",
                      "events": [
                        {
                          "introduced": "0"
                        },
                        {
                          "fixed": "2e7e8c4a7b318f4032493773732754e418279a14"
                        }
                      ],
                      "repo": "https://github.com/pygments/pygments"
                    },
                    {
                      "type": "ECOSYSTEM",
                      "events": [
                        {
                          "introduced": "1.1"
                        },
                        {
                          "fixed": "2.7.4"
                        }
                      ]
                    }
                  ],
                  "versions": [
                    "1.1",
                    "1.1.1",
                    "1.2",
                    "1.2.1",
                    "1.2.2",
                    "1.3",
                    "1.3.1",
                    "1.4",
                    "1.5",
                    "1.6",
                    "1.6rc1",
                    "2.0",
                    "2.0.1",
                    "2.0.2",
                    "2.0rc1",
                    "2.1",
                    "2.1.1",
                    "2.1.2",
                    "2.1.3",
                    "2.2.0",
                    "2.3.0",
                    "2.3.1",
                    "2.4.0",
                    "2.4.1",
                    "2.4.2",
                    "2.5.1",
                    "2.5.2",
                    "2.6.0",
                    "2.6.1",
                    "2.7.0",
                    "2.7.1",
                    "2.7.2",
                    "2.7.3"
                  ],
                  "database_specific": {
                    "source": "https://github.com/pypa/advisory-database/blob/main/vulns/pygments/PYSEC-2021-141.yaml"
                  }
                }
              ],
              "references": [
                {
                  "type": "WEB",
                  "url": "https://gist.github.com/b-c-ds/b1a2cc0c68a35c57188575eb496de5ce"
                },
                {
                  "type": "FIX",
                  "url": "https://github.com/pygments/pygments/commit/2e7e8c4a7b318f4032493773732754e418279a14"
                },
                {
                  "type": "WEB",
                  "url": "https://lists.debian.org/debian-lts-announce/2021/03/msg00024.html"
                },
                {
                  "type": "ADVISORY",
                  "url": "https://www.debian.org/security/2021/dsa-4878"
                },
                {
                  "type": "ADVISORY",
                  "url": "https://www.debian.org/security/2021/dsa-4889"
                },
                {
                  "type": "WEB",
                  "url": "https://lists.debian.org/debian-lts-announce/2021/05/msg00003.html"
                },
                {
                  "type": "WEB",
                  "url": "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/WSLD67LFGXOX2K5YNESSWAS4AGZIJTUQ/"
                },
                {
                  "type": "WEB",
                  "url": "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/GSJRFHALQ7E3UV4FFMFU2YQ6LUDHAI55/"
                },
                {
                  "type": "WEB",
                  "url": "https://lists.debian.org/debian-lts-announce/2021/05/msg00006.html"
                },
                {
                  "type": "ADVISORY",
                  "url": "https://github.com/advisories/GHSA-pq64-v7f5-gqh8"
                }
              ]
            },
            {
              "modified": "2023-11-08T04:10:25Z",
              "published": "2023-07-19T15:15:00Z",
              "schema_version": "1.6.0",
              "id": "PYSEC-2023-117",
              "aliases": [
                "CVE-2022-40896",
                "GHSA-mrwq-x4v8-fh7p"
              ],
              "details": "A ReDoS issue was discovered in pygments/lexers/smithy.py in pygments through 2.15.0 via SmithyLexer.",
              "affected": [
                {
                  "package": {
                    "ecosystem": "PyPI",
                    "name": "pygments",
                    "purl": "pkg:pypi/pygments"
                  },
                  "ranges": [
                    {
                      "type": "ECOSYSTEM",
                      "events": [
                        {
                          "introduced": "0"
                        },
                        {
                          "fixed": "2.15.1"
                        }
                      ]
                    }
                  ],
                  "versions": [
                    "0.10",
                    "0.11",
                    "0.11.1",
                    "0.5",
                    "0.5.1",
                    "0.6",
                    "0.7",
                    "0.7.1",
                    "0.8",
                    "0.8.1",
                    "0.9",
                    "1.0",
                    "1.1",
                    "1.1.1",
                    "1.2",
                    "1.2.1",
                    "1.2.2",
                    "1.3",
                    "1.3.1",
                    "1.4",
                    "1.5",
                    "1.6",
                    "1.6rc1",
                    "2.0",
                    "2.0.1",
                    "2.0.2",
                    "2.0rc1",
                    "2.1",
                    "2.1.1",
                    "2.1.2",
                    "2.1.3",
                    "2.10.0",
                    "2.11.0",
                    "2.11.1",
                    "2.11.2",
                    "2.12.0",
                    "2.13.0",
                    "2.14.0",
                    "2.15.0",
                    "2.2.0",
                    "2.3.0",
                    "2.3.1",
                    "2.4.0",
                    "2.4.1",
                    "2.4.2",
                    "2.5.1",
                    "2.5.2",
                    "2.6.0",
                    "2.6.1",
                    "2.7.0",
                    "2.7.1",
                    "2.7.2",
                    "2.7.3",
                    "2.7.4",
                    "2.8.0",
                    "2.8.1",
                    "2.9.0"
                  ],
                  "database_specific": {
                    "source": "https://github.com/pypa/advisory-database/blob/main/vulns/pygments/PYSEC-2023-117.yaml"
                  }
                }
              ],
              "references": [
                {
                  "type": "PACKAGE",
                  "url": "https://pypi.org/project/Pygments/"
                },
                {
                  "type": "WEB",
                  "url": "https://pyup.io/posts/pyup-discovers-redos-vulnerabilities-in-top-python-packages-part-2/"
                },
                {
                  "type": "WEB",
                  "url": "https://github.com/pygments/pygments/blob/master/pygments/lexers/smithy.py#L61"
                }
              ]
            }
          ],
          "groups": [
            {
              "ids": [
                "GHSA-9w8r-397f-prfh",
                "PYSEC-2021-140"
              ]
            },
            {
              "ids": [
                "GHSA-mrwq-x4v8-fh7p",
                "PYSEC-2023-117"
              ]
            },
            {
              "ids": [
                "GHSA-pq64-v7f5-gqh8",
                "PYSEC-2021-141"
              ]
            }
          ]
        }
      ]
    }
  ]
}
