{
  "results": [
    {
      "source": {
        "path": "/src/github.sbom.spdx.json",
        "type": "sbom"
      },
      "packages": [
        {
          "package": {
            "name": "mongodb",
            "version": "1.1.8",
            "ecosystem": "npm",
            "commit": ""
          },
          "vulnerabilities": [
            {
              "modified": "2020-08-31T18:51:01Z",
              "published": "2020-09-03T21:12:01Z",
              "schema_version": "1.6.0",
              "id": "GHSA-mh5c-679w-hh4r",
              "summary": "Denial of Service in mongodb",
              "details": "Versions of `mongodb` prior to 3.1.13 are vulnerable to Denial of Service. The package fails to properly catch an exception when a collection name is invalid and the DB does not exist, crashing the application.\n\n\n## Recommendation\n\nUpgrade to version 3.1.13 or later.",
              "affected": [
                {
                  "package": {
                    "ecosystem": "npm",
                    "name": "mongodb",
                    "purl": "pkg:npm/mongodb"
                  },
                  "ranges": [
                    {
                      "type": "SEMVER",
                      "events": [
                        {
                          "introduced": "0"
                        },
                        {
                          "fixed": "3.1.13"
                        }
                      ]
                    }
                  ],
                  "database_specific": {
                    "source": "https://github.com/github/advisory-database/blob/main/advisories/github-reviewed/2020/09/GHSA-mh5c-679w-hh4r/GHSA-mh5c-679w-hh4r.json"
                  }
                }
              ],
              "references": [
                {
                  "type": "WEB",
                  "url": "https://www.npmjs.com/advisories/1203"
                }
              ],
              "database_specific": {
                "cwe_ids": [],
                "github_reviewed": true,
                "github_reviewed_at": "2020-08-31T18:51:01Z",
                "nvd_published_at": null,
                "severity": "HIGH"
              }
            }
          ],
          "groups": [
            {
              "ids": [
                "GHSA-mh5c-679w-hh4r"
              ]
            }
          ]
        },
        {
          "package": {
            "name": "socket.io",
            "version": "0.9.10",
            "ecosystem": "npm",
            "commit": ""
          },
          "vulnerabilities": [
            {
              "modified": "2023-11-08T04:03:28Z",
              "published": "2021-01-20T21:22:37Z",
              "schema_version": "1.6.0",
              "id": "GHSA-fxwf-4rqh-v8g3",
              "aliases": [
                "CVE-2020-28481",
                "SNYK-JAVA-ORGWEBJARSBOWER-1056358",
                "SNYK-JAVA-ORGWEBJARSNPM-1056357",
                "SNYK-JS-SOCKETIO-1024859"
              ],
              "summary": "CORS misconfiguration in socket.io",
              "details": "The package socket.io before 2.4.0 are vulnerable to Insecure Defaults due to CORS Misconfiguration. All domains are whitelisted by default.",
              "affected": [
                {
                  "package": {
                    "ecosystem": "npm",
                    "name": "socket.io",
                    "purl": "pkg:npm/socket.io"
                  },
                  "ranges": [
                    {
                      "type": "SEMVER",
                      "events": [
                        {
                          "introduced": "0"
                        },
                        {
                          "fixed": "2.4.0"
                        }
                      ]
                    }
                  ],
                  "database_specific": {
                    "source": "https://github.com/github/advisory-database/blob/main/advisories/github-reviewed/2021/01/GHSA-fxwf-4rqh-v8g3/GHSA-fxwf-4rqh-v8g3.json"
                  }
                }
              ],
              "severity": [
                {
                  "type": "CVSS_V3",
                  "score": "CVSS:3.1/AV:N/AC:L/PR:L/UI:N/S:U/C:L/I:N/A:N"
                }
              ],
              "references": [
                {
                  "type": "ADVISORY",
                  "url": "https://nvd.nist.gov/vuln/detail/CVE-2020-28481"
                },
                {
                  "type": "WEB",
                  "url": "https://github.com/socketio/socket.io/issues/3671"
                },
                {
                  "type": "WEB",
                  "url": "https://github.com/socketio/socket.io/commit/f78a575f66ab693c3ea96ea88429ddb1a44c86c7"
                },
                {
                  "type": "WEB",
                  "url": "https://snyk.io/vuln/SNYK-JAVA-ORGWEBJARSBOWER-1056358"
                },
                {
                  "type": "WEB",
                  "url": "https://snyk.io/vuln/SNYK-JAVA-ORGWEBJARSNPM-1056357"
                },
                {
                  "type": "WEB",
                  "url": "https://snyk.io/vuln/SNYK-JS-SOCKETIO-1024859"
                }
              ],
              "database_specific": {
                "cwe_ids": [
                  "CWE-346",
                  "CWE-453"
                ],
                "github_reviewed": true,
                "github_reviewed_at": "2021-01-20T05:39:24Z",
                "nvd_published_at": "2021-01-19T15:15:00Z",
                "severity": "MODERATE"
              }
            }
          ],
          "groups": [
            {
              "ids": [
                "GHSA-fxwf-4rqh-v8g3"
              ]
            }
          ]
        }
      ]
    }
  ]
}
